GET http://localhost:3333/api/alunos

###
GET http://localhost:3333/api/alunos/3

###
POST http://localhost:3333/api/alunos
Content-Type: application/json

{
  "nome": "Joselito",
  "sobrenome": "Santos",
  "data_nascimento": "2003-07-10T03:00:00.000Z",
  "endereco": "Rua do Ingá, 811",
  "email": "joselito@semnocao.com",
  "celular": "16991915545"
}

###
PUT http://localhost:3333/api/alunos/24
Content-Type: application/json

{
  "nome": "Joselito",
  "sobrenome": "Freitas",
  "data_nascimento": "2003-07-10T03:00:00.000Z",
  "endereco": "Rua do Ingá, 001",
  "email": "joselito@semnocao.com",
  "celular": "16991915545"
}

###
DELETE http://localhost:3333/api/alunos/11